### ISSUE TITLE
Rotatiehoek ontbreek bij Annotatie

### ISSUE THREAD

**Issue by emacgillavry** [Geonovum/imkl2015-dev#4]
Zie ook rapport IMKL2015 - Objectcatalogus p.9. alleen relevant voor annotatieLabel en annotatiePunt. Zit niet in de brondata. In PHP script een default van "0" opvoeren?

**Comment by PalmJanssen** [comment]
Zetten we ook in brondata. Het blijft een optioneel attribuut.

**Comment by wilkoquak** [comment]
toegevoegd aan voorbeeldbestand
