### ISSUE TITLE
Rotatiehoek ontbreek bij Maatvoeringslabel

### ISSUE THREAD

**Issue by emacgillavry** [Geonovum/imkl2015-dev#5]
Niet beschikbaar in brondata van Paul (zit igg niet in tabel public.v_maatvoering_label). Misschien in PHP script een defaultwaarde van "0" meegeven?

**Comment by PalmJanssen** [comment]
We zetten een paar waardes in de dataset om het SLD te testen. In het model blijft het optioneel.

**Comment by emacgillavry** [comment]
Vang ik bovendien af met GeoServer Function PropertyExists. Let op: functies zijn specifiek voor een bepaalde software. Gelukkig heeft GeoServer deze functie, maar het kan zijn, dat andere software deze functie NIET ondersteunt.

**Comment by wilkoquak** [comment]
Toegevoegd aan voorbeeldbestand
